import java.io.File
import java.util.Properties
import org.gradle.api.tasks.testing.Test
import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    kotlin("plugin.serialization") version "2.3.0"
    alias(libs.plugins.googleServices)
    alias(libs.plugins.firebaseCrashlytics)
    alias(libs.plugins.kover)
}

// ---------------------------------------------------------------------------
// Build provenance — mirrors the desktop app's helpers in ChurchPresenter's
// composeApp/build.gradle.kts.
//
// The app is open-source and hardcodes the live-map ping URL, so a fork built
// from source pings churchpresenter.org with a payload identical to an official
// install. Stamping the build's git origin and state lets the server tell them
// apart (see the build_channel column and api/ping.ts in the website repo).
// Attribution for honest forks, not authentication — anyone can patch these
// constants out. Every helper falls back rather than failing the build.
// ---------------------------------------------------------------------------

/**
 * Runs a git command, returning null when git is missing or exits non-zero.
 *
 * Uses providers.exec rather than ProcessBuilder: this project has the
 * configuration cache enabled, which forbids starting external processes at
 * configuration time. providers.exec is the supported route — Gradle tracks the
 * result as a configuration-cache input instead of rejecting it.
 *
 * stderr is captured separately and discarded, so git's "fatal: not a git
 * repository" never comes back looking like a real value.
 */
fun gitOutput(vararg args: String): String? {
    return try {
        val result = providers.exec {
            commandLine("git", *args)
            workingDir = rootProject.projectDir
            isIgnoreExitValue = true
        }
        if (result.result.get().exitValue != 0) null
        else result.standardOutput.asText.get().trim()
    } catch (_: Exception) { null }
}

// Matches the server's REPO_RE — anything else is stored as 'unknown' there, so
// there's no point sending it.
val repoSlugRegex = Regex("^[a-z0-9][a-z0-9._-]{0,38}/[a-z0-9][a-z0-9._-]{0,99}$")

/**
 * Parses a git remote URL down to a lowercase "owner/name" slug.
 *
 * Only the slug is ever sent — never the raw URL, which can embed credentials
 * (https://user:token@github.com/...). Handles https://, ssh:// and scp-style
 * (git@host:owner/name) remotes; anything else yields "unknown".
 */
fun parseRepoSlug(remoteUrl: String): String {
    val trimmed = remoteUrl.trim().removeSuffix(".git").trimEnd('/')
    if (trimmed.isEmpty()) return "unknown"
    val path = when {
        trimmed.contains("://") -> trimmed.substringAfter("://").substringAfter('/', "")
        trimmed.contains(':') -> trimmed.substringAfter(':')
        // A bare filesystem path is a local clone, not an identifiable remote.
        else -> return "unknown"
    }
    val parts = path.split('/').filter { it.isNotEmpty() }
    if (parts.size < 2) return "unknown"
    val slug = "${parts[parts.size - 2]}/${parts[parts.size - 1]}".lowercase()
    return if (repoSlugRegex.matches(slug)) slug else "unknown"
}

// Provenance is a property of the build, not of the target, so unlike
// isDebugBuild this needs no expect/actual — one generated file in commonMain
// serves Android, iOS and web alike.
//
// Only the two raw git facts are baked in here. Whether the build is a "release"
// is decided at runtime in BuildUtils.kt from the per-target isDebugBuild, which
// is far more reliable than guessing from Gradle task names across three
// different toolchains.
val generateProvenanceConfig by tasks.registering {
    val repoSlug = parseRepoSlug(gitOutput("remote", "get-url", "origin") ?: "")
    val commitHash = gitOutput("rev-parse", "--short=12", "HEAD") ?: "unknown"
    val hasGit = gitOutput("rev-parse", "--git-dir") != null
    val isDirty = !gitOutput("status", "--porcelain").isNullOrEmpty()
    val outputDir = layout.buildDirectory.dir("generated/provenance")

    // Git state can change with no file edit Gradle can see, so never cache.
    outputs.upToDateWhen { false }
    outputs.dir(outputDir)

    doLast {
        val dir = outputDir.get().asFile
            .resolve("com/church/presenter/churchpresentermobile/util")
        dir.mkdirs()
        dir.resolve("BuildProvenance.kt").writeText(
            """
            |package com.church.presenter.churchpresentermobile.util
            |
            |// Generated by the generateProvenanceConfig task — do not edit.
            |internal object BuildProvenance {
            |    const val REPO_SLUG = "$repoSlug"
            |    const val COMMIT_HASH = "$commitHash"
            |    const val HAS_GIT = $hasGit
            |    const val IS_DIRTY = $isDirty
            |}
            """.trimMargin()
        )
    }
}

// ---------------------------------------------------------------------------
// Code-coverage (Kover) — measured on the Android unit-test JVM (where commonTest
// runs). Scoped to the reliably-JVM-measurable logic: `model`, `network` and
// `present` (the standalone presenter's routing/slide logic — pure by design;
// the platform-specific output sinks live behind expect/actual leaves that are
// named in the `classes` exclusion list below).
//
// The `viewmodel` package is EXCLUDED from the measured number, not because it's
// untested — it's fully covered and gated by the `jsBrowserTest` CI job — but
// because ViewModel tests install a test Main dispatcher (viewModelScope), and the
// Android unit-test JVM has no Dispatchers.Main without Robolectric. So VM tests
// are excluded from the Android run (see the Test filter below) and, to keep the %
// honest, from the Kover scope too. UI/App.kt/platform/generated are excluded as
// non-unit-testable. Report: composeApp/build/reports/kover/.
// ---------------------------------------------------------------------------
kover {
    reports {
        filters {
            excludes {
                // Compose UI is not unit-tested — drop every @Composable plus the ui package.
                annotatedBy("androidx.compose.runtime.Composable")
                packages(
                    "com.church.presenter.churchpresentermobile.ui",
                    // Covered on the JS gate, not measurable on the Android JVM (no Main dispatcher).
                    "com.church.presenter.churchpresentermobile.viewmodel",
                    // Platform glue + constants (Logger/Analytics/CrashReporting/RemoteConfig/BuildUtils).
                    "com.church.presenter.churchpresentermobile.util",
                )
                classes(
                    // App.kt Composable + its generated lambda classes ($App$…), and singletons.
                    "*AppKt*",
                    "*ComposableSingletons*",
                    // Generated Compose resource accessors.
                    "churchpresentermobile.composeapp.generated.resources.*",
                    // Data fixtures & WebSocket transport loop — not unit-test targets.
                    "*DemoData*",
                    "*ServerEventService*",
                    "*PingReporter*",
                    // Platform factories / storage / Android infra (share model|network packages).
                    "*HttpClientFactory*",
                    "*SettingsStorage*",
                    "*MainActivity*",
                    "*ChurchPresenterApp*",
                    "*FirebasePushService*",
                    // Platform capability flags — three constants per target, no logic.
                    "*PlatformCapabilities*",
                    // Output sinks are platform windows/servers, not unit-test targets;
                    // the routing and slide logic they serve is tested in `present`.
                    "*ExternalDisplaySink*",
                    "*SlidePresentation*",
                    "*PresentationOwners*",
                    "*ActivityHolder*",
                    // Embedded server, socket/interface probing, and the OS
                    // keep-alive hooks — all platform I/O behind narrow seams.
                    // The pure parts (PortAllocator, WebAssets) ARE measured.
                    "*LocalWebServer*",
                    "*WebPageSink*",
                    "*NetworkInfo*",
                    "*PresentationKeepAlive*",
                    "*PresentationForegroundService*",
                    // Platform file I/O. The repository logic that sits on top of
                    // it IS measured, via InMemoryFileStorage.
                    "*FileStore*",
                    "*DocumentIO*",
                )
            }
        }
        // Enforced floor for the scoped model+network logic (currently ~82% line).
        // Set to 80 so normal churn doesn't break CI; ratchet toward 85 as the
        // remaining error branches / upload methods get covered. `koverVerify`
        // is run in CI (see .github/workflows/tests.yml).
        verify {
            rule {
                minBound(80)
            }
        }
    }
}

// The Android unit-test JVM has no Dispatchers.Main (no Looper / Robolectric), so
// ViewModel tests that install a test main dispatcher can't run there — they run on
// the jsBrowserTest gate instead. Exclude them from JVM (Android) unit-test tasks so
// the Kover coverage run over model+network is green. JS/Wasm test tasks are not of
// type `Test`, so this filter does not affect them.
tasks.withType<Test>().configureEach {
    filter {
        excludeTestsMatching("*ViewModelTest")
        isFailOnNoMatchingTests = false
    }
}

// ---------------------------------------------------------------------------
// Generates the actual isDebugBuild for the JS/WasmJs targets (webMain), since
// neither has a runtime debug flag analogous to Android's BuildConfig.DEBUG.
// Mirrors the desktop app's generateBuildConfig task: dev-vs-prod is inferred
// from which Gradle task was requested. Every relevant JS/Wasm compile task
// literally contains "Development" or "Production" (e.g.
// compileDevelopmentExecutableKotlinJs vs compileProductionExecutableKotlinJs),
// except the CI distribution tasks (jsBrowserDistribution/wasmJsBrowserDistribution,
// used by .github/workflows/web-deploy.yml) which build the production executable
// under the hood without saying "production" in the task name itself — hence the
// extra "distribution" check.
// ---------------------------------------------------------------------------
val generateWebBuildConfig by tasks.registering {
    val isRelease = gradle.startParameter.taskNames.any { task ->
        val t = task.lowercase()
        t.contains("production") || t.contains("distribution")
    }
    val outputDir = layout.buildDirectory.dir("generated/webbuildconfig")
    // isRelease depends on the requested task names, not on any tracked file input,
    // so Gradle's normal up-to-date check can't detect when it needs to rerun —
    // always re-run (same as desktop's generateBuildConfig task).
    outputs.upToDateWhen { false }
    outputs.dir(outputDir)

    doLast {
        val dir = outputDir.get().asFile
            .resolve("com/church/presenter/churchpresentermobile/util")
        dir.mkdirs()
        dir.resolve("WebBuildUtils.kt").writeText(
            """
            |package com.church.presenter.churchpresentermobile.util
            |
            |actual val isDebugBuild: Boolean = ${!isRelease}
            """.trimMargin()
        )
    }
}

kotlin {
    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    // Extend the default hierarchy with a "web" intermediate source set shared
    // by JS and WasmJS targets.  Using the hierarchy-template API (instead of
    // manual dependsOn calls on jsMain / wasmJsMain) is required in Kotlin 2.x:
    // explicit dependsOn edges on those source sets suppress the default
    // hierarchy template entirely, which disconnects iosMain from all iOS
    // compilations and causes "no actual declaration for Native" errors.
    @OptIn(ExperimentalKotlinGradlePluginApi::class)
    applyDefaultHierarchyTemplate {
        common {
            group("web") {
                withJs()
                withWasmJs()
            }
            // Android + iOS share everything that needs real device APIs the
            // browser has no analogue for — chiefly the standalone presenter's
            // embedded HTTP/WebSocket server. One Ktor CIO implementation
            // serves both (JVM artifact on Android, Kotlin/Native on iOS).
            group("mobile") {
                withAndroidTarget()
                withIos()
            }
        }
    }

    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
            freeCompilerArgs += listOf("-Xbinary=bundleId=com.church.presenter.churchpresentermobile")
        }
    }

    js {
        browser {
            // Headless Chrome so `jsBrowserTest` runs the commonTest suite on CI
            // (and locally) without a visible browser window.
            testTask {
                useKarma { useChromeHeadless() }
            }
        }
        binaries.executable()
    }

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser()
        binaries.executable()
    }

    sourceSets {
        // NOTE: webMain is created automatically by the applyDefaultHierarchyTemplate
        // call above — do NOT add dependsOn(webMain) to jsMain or wasmJsMain here.

        // Provides the actual isDebugBuild for both JS and WasmJs from one generated
        // file (see generateWebBuildConfig above) — an actual declared on this shared
        // intermediate source set satisfies the expect for both leaf targets. "web" is
        // a custom hierarchy-template group (not a built-in name like jsMain/androidMain),
        // so it has no typesafe accessor — look it up by name instead.
        getByName("webMain") {
            kotlin.srcDir(generateWebBuildConfig.map { layout.buildDirectory.dir("generated/webbuildconfig") })
        }

        // Build provenance for the live-map ping (see generateProvenanceConfig
        // above). Unlike isDebugBuild this is target-independent, so it lives in
        // commonMain and every target compiles the same generated file.
        commonMain {
            kotlin.srcDir(generateProvenanceConfig.map { layout.buildDirectory.dir("generated/provenance") })
        }

        getByName("mobileMain").dependencies {
            // Embedded presentation server — standalone mode only.
            implementation(libs.ktor.server.core)
            implementation(libs.ktor.server.cio)
            implementation(libs.ktor.server.websockets)
        }

        jsMain.dependencies {
            implementation(libs.ktor.client.js)
        }

        androidMain.dependencies {
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.activity.compose)
            implementation(libs.ktor.client.okhttp)
            implementation(libs.androidx.core.splashscreen)
            // Firebase — BOM version is enforced via the top-level dependencies block
            implementation(libs.firebase.crashlytics)
            implementation(libs.firebase.messaging)
            implementation(libs.firebase.analytics)
            implementation(libs.firebase.config)
            implementation(libs.firebase.inappmessaging)
            implementation(libs.sentry.android)
            implementation(libs.play.review)
            implementation(libs.play.app.update)
            // QR code scanner — no camera permission required, Google provides the UI
            implementation("com.google.android.gms:play-services-code-scanner:16.1.0")
        }
        iosMain.dependencies {
            implementation(libs.ktor.client.ios)
        }
        commonMain.dependencies {
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            @OptIn(org.jetbrains.compose.ExperimentalComposeLibrary::class)
            implementation(compose.materialIconsExtended)
            implementation(libs.coil.compose)
            implementation(libs.coil.network.ktor)
            implementation(libs.compose.ui)
            implementation(libs.compose.components.resources)
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodelCompose)
            implementation(libs.androidx.lifecycle.runtimeCompose)
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.contentNegotiation)
            implementation(libs.ktor.serialization.json)
            implementation(libs.ktor.client.websockets)
            // QR generation for the standalone display URL (QrScanButton only scans).
            implementation(libs.qrose)
            implementation(libs.kotlinx.serialization)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.ktor.client.mock)
            implementation(libs.kotlinx.coroutines.test)
        }
    }
}

// ---------------------------------------------------------------------------
// Signing configuration — loaded from the private signing repo.
// Resolution order (first found wins):
//   1. Individual Gradle project properties  (-Pandroid.signing.*)
//   2. signing.properties file in the repo pointed to by signing.repo.path
//      (set in local.properties or via SIGNING_REPO_PATH env variable)
// ---------------------------------------------------------------------------
val signingRepoPath: String? =
    findProperty("signing.repo.path")?.toString()
        ?: System.getenv("SIGNING_REPO_PATH")
        ?: run {
            val localProps = Properties()
            val localPropsFile = rootProject.file("local.properties")
            if (localPropsFile.exists()) localProps.load(localPropsFile.inputStream())
            localProps.getProperty("signing.repo.path")
        }

val signingProps = Properties()
val signingPropsFile = signingRepoPath?.let { file("$it/signing.properties") }
if (signingPropsFile?.exists() == true) {
    signingProps.load(signingPropsFile.inputStream())
}

fun signingProp(key: String, gradleKey: String = "android.signing.$key"): String? =
    findProperty(gradleKey)?.toString() ?: signingProps.getProperty(key)

android {
    namespace = "com.church.presenter.churchpresentermobile"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "com.church.presenter.churchpresentermobile"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = 16
        versionName = "1.0.15"
    }
    testOptions {
        // Let commonTest run on the Android unit-test JVM (used by the best-effort
        // Kover coverage job): unmocked android.jar methods return defaults (e.g.
        // Log.* no-ops) instead of throwing.
        unitTests.isReturnDefaultValues = true
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }

    // Register release signing config only when credentials are available.
    val storeFileProp  = signingProp("storeFile")
    val storePassProp  = signingProp("storePassword")
    val keyAliasProp   = signingProp("keyAlias")
    val keyPassProp    = signingProp("keyPassword")

    if (storeFileProp != null && storePassProp != null && keyAliasProp != null && keyPassProp != null) {
        signingConfigs {
            create("release") {
                // storeFile may be relative (resolved against signing repo) or absolute.
                // Use java.io.File to check absoluteness of the raw string before
                // letting Gradle's file() resolve it (Gradle always resolves relative
                // paths against the project dir, which would be wrong here).
                val ksFile = if (File(storeFileProp).isAbsolute) {
                    file(storeFileProp)
                } else {
                    file("$signingRepoPath/$storeFileProp")
                }
                storeFile     = ksFile
                storePassword = storePassProp
                keyAlias      = keyAliasProp
                keyPassword   = keyPassProp
            }
        }
    } else {
        logger.warn(
            "[ChurchPresenter] Release signing config not found. " +
            "Set signing.repo.path in local.properties or SIGNING_REPO_PATH env variable."
        )
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            signingConfigs.findByName("release")?.let { signingConfig = it }
        }
    }
    buildFeatures {
        buildConfig = true
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

dependencies {
    debugImplementation(libs.compose.uiTooling)
    // Firebase BOM — constrains all firebase-* library versions for the Android target
    add("androidMainImplementation", platform(libs.firebase.bom))
}

// ---------------------------------------------------------------------------
// NOTE on Sentry source-context upload: the io.sentry.android.gradle plugin
// (which provides that feature) isn't Kotlin-Multiplatform-aware — applying it
// to this module leaks Android-only companion artifacts (sentry-compose-android,
// sentry-kotlin-extensions) into the JS/WasmJs dependency graph and breaks
// resolution there, regardless of its autoInstallation/tracingInstrumentation
// toggles. So it's deliberately not applied here; Sentry itself works fully via
// the plain io.sentry:sentry-android dependency in androidMain below — this
// only costs the "source context" (readable source lines in the Sentry
// dashboard), not any actual crash/error reporting functionality.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Disable ART startup-profile compilation tasks to prevent
// INSTALL_BASELINE_PROFILE_FAILED when installing the APK on devices /
// emulators that cannot compile the embedded binary profile.
// The gradle.properties flag `android.experimental.art.profile.default.warp`
// handles this on newer AGP versions; the configureEach block below is a
// belt-and-suspenders guard for all AGP versions.
// ---------------------------------------------------------------------------
tasks.configureEach {
    if (name.contains("ArtProfile", ignoreCase = true)) {
        enabled = false
    }
}

