platform :ios, '16.0'

target 'iosApp' do
  use_frameworks!

  pod 'FirebaseAnalytics',    '~> 11.8'
  pod 'FirebaseCrashlytics',  '~> 11.8'
  pod 'FirebaseMessaging',    '~> 11.8'
  pod 'FirebaseRemoteConfig', '~> 11.8'
end

# Disable code-signing for all Pod targets.
# Without this, passing CODE_SIGN_STYLE=Manual or PROVISIONING_PROFILE_SPECIFIER
# on the xcodebuild command line causes errors on Firebase/library targets that
# do not support provisioning profiles.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['CODE_SIGNING_ALLOWED']  = 'NO'
      config.build_settings['CODE_SIGN_IDENTITY']    = ''
    end
  end
end
