package com.church.presenter.churchpresentermobile.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Metadata for a single chapter inside a [BibleBook], as returned by GET /api/bible.
 */
@Serializable
data class BibleChapterInfo(
    val chapter: Int,
    @SerialName("verse-total") val verseTotal: Int? = null
)

/**
 * A single book in the Bible, as returned by GET /api/bible.
 * The server returns chapters as a list of [BibleChapterInfo] objects
 * and the chapter count in "chapter-total".
 */
@Serializable
data class BibleBook(
    // id / name may appear under different keys — all optional with defaults
    val id: String? = null,
    val name: String? = null,
    @SerialName("book-name") val bookName: String? = null,
    @SerialName("book_name") val bookNameAlt: String? = null,
    val testament: String? = null,
    @SerialName("chapter-total") val chapterTotal: Int? = null,
    @SerialName("chapter_count") val chapterCount: Int? = null,
    // chapters is a list of objects, NOT an Int
    val chapters: List<BibleChapterInfo>? = null
) {
    /** Best available display name. */
    val displayName: String
        get() = listOfNotNull(name, bookName, bookNameAlt, id)
            .firstOrNull { it.isNotBlank() } ?: "Unknown"

    /** Best available identifier for URL construction. */
    val bookId: String
        get() = id ?: bookName ?: bookNameAlt ?: name ?: displayName

    /** Total number of chapters in this book. */
    val totalChapters: Int
        get() = chapterTotal ?: chapterCount ?: chapters?.size ?: 0
}

/** Top-level response from GET /api/bible */
@Serializable
data class BibleBooksResponse(
    val books: List<BibleBook>? = null,
    val bible: List<BibleBook>? = null
) {
    val allBooks: List<BibleBook>
        get() = books?.takeIf { it.isNotEmpty() } ?: bible ?: emptyList()
}

/** A single verse within a chapter. */
@Serializable
data class BibleVerse(
    val verse: Int? = null,
    @SerialName("verse-number") val verseNumber: Int? = null,
    @SerialName("verse_number") val verseNumberAlt: Int? = null,
    val text: String? = null,
    val content: String? = null
) {
    /** Best available verse number. */
    val number: Int get() = verse ?: verseNumber ?: verseNumberAlt ?: 0

    /** Best available verse text. */
    val displayText: String get() = text?.takeIf { it.isNotBlank() } ?: content ?: ""
}

/** Response from GET /api/bible/{bookId}/{chapter} */
@Serializable
data class BibleChapterResponse(
    val book: String? = null,
    val chapter: Int? = null,
    val verses: List<BibleVerse>? = null,
    val content: List<BibleVerse>? = null
) {
    val allVerses: List<BibleVerse>
        get() = verses?.takeIf { it.isNotEmpty() } ?: content ?: emptyList()
}

/**
 * The `item` object sent in the body of POST /api/project and POST /api/schedule/add.
 *
 * Server parses via RemoteItemRequest { item: RemoteItemDto }.
 * A BibleVerseItem is created when bookName + chapter + verseNumber are all present.
 *
 * @param bookName    Required — book display name (e.g. "Genesis").
 * @param chapter     Required — 1-based chapter number.
 * @param verseNumber Required — 1-based verse number.
 * @param verseText   Optional — on-screen lyric text; defaults to "" on the server if omitted.
 * @param id          Optional — UUID auto-generated by the server if blank or missing.
 */
@Serializable
data class BibleItemPayload(
    val id: String? = null,
    val bookName: String,
    val chapter: Int,
    val verseNumber: Int,
    val verseText: String = "",
    val verseRange: String? = null
)

/** Wrapper request body for POST /api/project and POST /api/schedule/add. */
@Serializable
data class ProjectBibleRequest(val item: BibleItemPayload)

/**
 * Request body for POST /api/bible/select.
 * Sent directly (no "item" wrapper) — fires instantly without an approval dialog.
 */
@Serializable
data class BibleSelectRequest(
    val bookName: String,
    val chapter: Int,
    val verseNumber: Int,
    val verseText: String = "",
    val verseRange: String? = null
)


